// This file is generated by Astro DB
declare module 'astro:db' {
	export const Comment: import("@astrojs/db/runtime").Table<
		"Comment",
		{"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Comment","primaryKey":false,"optional":false}},"body":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"body","collection":"Comment","primaryKey":false,"optional":false}}}
	>;
	export const Reactions: import("@astrojs/db/runtime").Table<
		"Reactions",
		{"postSlug":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"postSlug","collection":"Reactions","primaryKey":false,"optional":false}},"emoji":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"emoji","collection":"Reactions","primaryKey":false,"optional":false}},"count":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"count","collection":"Reactions","primaryKey":false,"optional":false}}}
	>;
}
